# This workflow will install Python dependencies and run unittests with 2 Python versions

name: ci-django-unittests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, '3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install requirements dependencies
        run: |
          python -m pip install -r requirements-client.txt         
      - name: Run unittests
        run: |
          python -m unittest tests.tests_api
